### ISSUE TITLE
Issue building minimal example

### ISSUE THREAD

**Issue by Involture** [odata2ts/odata2ts#119]
I am trying to build a minimal exemple but I get an error.

I am pretty sure it is a configuration problem on my side and it has nothing to do with your library but I have don't know where to seek help except there.
Sorry in advance for opening an issue

package.json 
```
{
  "devDependencies": {
    "@odata2ts/odata2ts": "^0.18.2",
    "typescript": "^4.9.4"
  },
  "dependencies": {
    "@odata2ts/axios-odata-client": "^0.5.1",
    "@types/node": "^18.11.18"
  },
  "scripts": {
    "gen-odata": "npx odata2ts -d -s .\\odataMeta\\odata_v2_meta.xml -o .\\gen\\odataV2"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2016",
    "lib": ["esnext"],
    "module": "commonjs",
    "baseUrl": "./src", 
    "outDir": "./build",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true, 
    "strict": true, 
    "skipLibCheck": false
  }
}
```

src/main.ts
```
import { ODataService } from "../gen/odataV2/ODataService"
import { AxiosODataClient } from "@odata2ts/axios-odata-client"

const axiosClient = new AxiosODataClient()
const dataService = new ODataService(axiosClient, _SomeUrl_)
```

The objects are built correctly when I invoke `npm run gen-odata`
Invoking `tsc` does not raise any error and generate main.js in the build folder

but then invoking `node.exe .\build\main.js` raises the following error
```
Uncaught TypeError TypeError: odata_service_1.EntityServiceResolver is not a constructor
    at createEntityserviceResolver (c:\Users\mjanin\Documents\ProgramingProjects\node-api-tester\gen\odataV2\service\EntityService.js:52:12)
    at ODataService (c:\Users\mjanin\Documents\ProgramingProjects\node-api-tester\gen\odataV2\ODataService.js:255:71)
    at <anonymous> (c:\Users\mjanin\Documents\ProgramingProjects\node-api-tester\build\main.js:6:21)
    at Module._compile (internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (internal/modules/cjs/loader:1213:10)
    at Module.load (internal/modules/cjs/loader:1037:32)
    at Module._load (internal/modules/cjs/loader:878:12)
    at executeUserEntryPoint (internal/modules/run_main:82:12)
    at <anonymous> (internal/main/run_main_module:23:47)
```

Any help is appreciated,
Thank for your work, this package looks dope

**Comment by texttechne** [comment]
Hi @Involture, 
opening a ticket is absolutely fine with me. The project is still lacking a lot of documentation...

First off, you can take a look at the examples, there's a folder on the root level. The default example would be the [Trippin service](https://github.com/odata2ts/odata2ts/tree/main/examples/trippin).

Regarding your package.json:
* you're missing `@odata2ts/odata-service` as regular dependency, I'd guess that's the problem
* and the script could be simplified as you don't need npx and can use forward slashes (also supported by windows) `"gen-odata": "odata2ts -d -s ./odataMeta/odata_v2_meta.xml -o ./gen/odataV2"`
* furthermore I would suggest to use the config file `odata2ts.config.ts`: [some documentation](https://github.com/odata2ts/odata2ts/tree/main/packages/odata2ts#configuration-file)

Hope this helps. Feel free to ask more questions and thanks for the kind words.

**Comment by Involture** [comment]
Thank you for your quick answer,

1. I makes sense that I need data-service as a regular dependency. However I still can't compile :s
In the trippin service's package.json you added among others the following dependencies :
```
  "dependencies": {
    "@odata2ts/odata-service": "^0.13.0"
  },
  "devDependencies": {
    "@odata2ts/odata2ts": "^0.18.2",
  },
```
so I added the same to my project.

Then `@odata2ts/odata2ts@0.18.2/package.json` has
```
  "peerDependencies": {
    "@odata2ts/odata-service": "^0.11.0"
  },
```

Npm warns me that this peer dependency is conflicting !
So I first try downgrading odata-service in my package.json to version ^0.11.0
I regenerate artifacts with odata2ts
Then compile with tsc and :

**Comment by Involture** [comment]
So after disabling the library type checking I tried querying an EntitySet with the following :
```
const promise = dataService.Candidate.get().query().then(
	(val) => val.data
)

export default promise
```
the promise yields the expected data
However typing seems to be dead.
The compiler produces the following main.d.ts:
```
declare const promise: Promise<import("@odata2ts/odata-core").ODataCollectionResponseV2<any> | import("@odata2ts/odata-core").ODataCollectionResponseV4<any>>;
export default promise;
```

So typing information for the entity.

**Comment by Involture** [comment]
I built the trippin example, and compared the generated files with mines.
There is definitly a problem in the service generation for my project that doesnt occure for trippin.

The problem seems to be only for the "toplevel service" though

ODataService.d.ts declares the user property as such
```
User: import("@odata2ts/odata-service").EntityServiceResolver<ODataClient<any>, import("./SFODataModel").UserIdModel, import("@odata2ts/odata-service").EntityTypeServiceV2<ODataClient<any>, any, any, any> | import("@odata2ts/odata-service").EntityTypeServiceV4<ODataClient<any>, any, any, any>, import("@odata2ts/odata-service").EntitySetServiceV2<ODataClient<any>, any, any, any, any, any> | import("@odata2ts/odata-service").EntitySetServiceV4<ODataClient<any>, any, any, any, any, any>>;
```

However, if I understand correctly, it should import service/UserModelService and use it as return type
service/UserModelService seems to be correctly generated (there is no 'any' type everywhere).

Next I will be trying to import services manually and use them without going through the top level service

**Comment by texttechne** [comment]
I'll try to take a look this evening / night.

You might also try to generate TS files instead of js_dts. You need to generate them into the src folder or expand your tsconfig.json accordingly. That's most often easier to read.

If you could send me your metadata.xml I could take a better look into the problem.

Sorry for the hassle.

**Comment by texttechne** [comment]
Hi @Involture,
the peer dependencies of `odata2ts` were plainly wrong, because they're not auto updated by lerna. I've specified the correct versions and published a new version for now. So you could update to get rid of the incorrect peer deps warnings.

The real fix will be a refactoring of the release process, so I'll create a new ticket for that as well. Thanks for bringing up that issue!

Otherwise I cannot reproduce any of your problems. So I assume (as you also seem to imply) that it's caused by your code.
I would need your metadata file to further investigate.

I have the following suggestions as areas of investigation for you:
* check in your metadata file that all properties and parameters have a valid `Type="Edm..."` attribute 
* is your metadata comprised of multiple schema` elements (e.g. `<Schema Namespace="Trippin" ...`)?
* try to generate TS files instead, then you have the complete control regarding TS compiler settings

**Comment by Involture** [comment]
Thank you very much for fixing the dependency that quickly. I'll investigate the things you listed and if I still have some problem, I'll create a true reproductible minimal example and give a repo link there.

**Comment by Involture** [comment]
I had some time to investigate further? I solved some problems but created new ones.

1. The types are correctly generated now that I use `EmitModes.ts`
2. I though that `Edm.Int64` being mapped to `string` instead of `number` was a mistake but then I realized that `number` does not cover the whole Int64 range so I figured it may be intentional ?
3. I figured odata2ts uses the `Nullable` attribute to build `EditableXXX` types. While it is sensible, the service I use is using other custom attributes to tag properties that are required, or editable. I am still debatting between erasing types for edit operations, patching the edm file, or try and patch your library to fix the issue

I understand that you need a metadata file to help me further. I failed to produce a minimal one (despite my best effort, I couldn't get the ones I wrote to parse). Also, I intend to use your library for corporate work and the service I use is proprietary, so I cannot upload the metadata to github.
However, If you are interested in taking a look at at my issues, I could send the file to you via email or any other private channel.

Even if the typing only works for half the requests, I can always erase types and this is still better than any other odata client lib, so once again : thank you for your work.

**Comment by texttechne** [comment]
### Regarding Typing 
you're right, but then again that wouldn't explain why `Int.32` is also typed as string; and to make things more weired, in V4 every number type is typed as number... I've documented this stuff in [odata-core](https://github.com/odata2ts/odata2ts/tree/main/packages/odata-core).

By the way, you can use [converter-v2-to-v4](https://github.com/odata2ts/converter/tree/main/packages/converter-v2-to-v4) to get to the same types as V4. And you can [write any type converter you want](https://github.com/odata2ts/converter/tree/main/packages/converter-api).

### Regarding the Editable Problem
I would be highly interested in the way your EDM description works and would like to see if odata2ts could support your use case.
I've updated my profile to show my email address now.

**Comment by texttechne** [comment]
And I almost forgot: You can already control which props are editable and which are not.
You need to use the config file for that:
* The [booskhop example](https://github.com/odata2ts/odata2ts/blob/main/examples/bookshop/odata2ts.config.ts#L45) uses this setting
  * propertiesByName also allows to specify property names as RegExps
* [This is the issue](https://github.com/odata2ts/odata2ts/issues/15) regarding that functionality

Otherwise I haven't documented this functionality yet. Well, probably on the interface itself and in tests...

**Comment by Involture** [comment]
### Typing
I didn't express myself correctly but the `Edm.Int32` properties are correctly mapped to the `number` type.
I will take a look at the type converters, it should solve my problem

### Editable properties
You assumed correctly about the custom attributes.
I will take a look at the propertiesByName setting.

### Other things (very descriptive title)
In general the service I am trying to interface with seems to take some liberties with the OData standard. I list a few of them below worded in a general fashion for public reference. I will also send you the Edm file this evening, so you can look at those issues with concrete data.

- Some FunctionImport declare no parameter but expect some payload (indicated by a custom attribute)
- The edm file contains two Schema with some forward references
- Expanded collection properties responses are represented by a JSON array encapsulated in a `{ results: [ ... ] }` object (and it seems to be in contradiction with the OData v2 standard if the only exemple given by [the documentation](https://www.odata.org/documentation/odata-version-2-0/json-format/) is to be trusted (see section 9))
- Expanded collections and entities reponses often contain metadata, and it is unclear to me if it is part of [the standard](https://www.odata.org/documentation/odata-version-2-0/json-format/) or not

**Comment by texttechne** [comment]
Ok, you raise a couple of issues here, which deserve their own tickets. It would be much appreciated, if you would be willing to create some of them as you brought them up; well, at least as far as you need these features.

### Converting `Int64`
My mistake, saying that `Edm.Int32` as being mapped to string in V2. Everything EXCEPT `Int32` and `Int16` is mapped to string according to the spec. 

If you're confronted with `Int64`, I planned to build a converter to convert that to JS' new `BigInt` type: [MDN ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). 
That should be pretty straightforward.

If you're sure that JS' number type is sufficient, then go with the v2-to-v4-converter.

### FunctionImport with Unanounced Payload
According to the spec (see [Operations](https://www.odata.org/documentation/odata-version-2-0/operations/), chapter 3.3) the concept of "open types" does exist:
> As discussed in [[OData-Core]](https://www.odata.org/documentation/odata-version-2-0/overview) the OData data model supports open types for Entries. An entry of an open type may have extra properties (dynamic properties) in addition to those statically declared in metadata.

I've respected that in most cases. You seem to be confronted with an edge case: No parameters at all, but hidden payload. So the generated operations would need to allow for passing parameters even if the metadata specifies no params at all. 

But to be sure, in the end you will probably be forced to `ts-ignore` the function call, but at least you can use the function.

### Better Support for Multiple Schemas
The current implementation for supporting multiple schemas is more like a hack than anything else. However, I would need examples to see how the schemas reference each other. So I'll need to check your example here...

### Expanded Collections with Extra Result Wrapping
I think we've hit this problem once. I wanted to investigate further, but didn't find the time yet.
So it's great that you're confronted with this issue as well to confirm the existence of this problem.

How do expanded entities behave? No problems there, so it only occurs with collections?

The extra metadata you mention for expanded entites and collections is probably part of this. And I don't think that the specification tells us anything in this regard. An example of such an output would be great.

**Comment by Involture** [comment]
I have been quite buisy this week end but I am willing to open different issues with proper formatting and exemples tomorrow (although you already started with the result wrapping one)

**Comment by texttechne** [comment]
Sorry for the mixed message. Would be really cool if you create the issues you're confronted with. No pressure there, at least that wasn't the intention! I probably move in my own pace and thus created the ticket about extra result wrapping as it would be the next on my agenda...

In the meantime I've created a proper documentation site: [https://odata2ts.github.io/](https://odata2ts.github.io/). Of course, it's not complete yet, but they're covering the issues you had, I hope. I would really appreciate any feedback on this.

In any case, all your issues and remarks are super helpful!

**Comment by Involture** [comment]
Now that everything mentionned in this issue is dispatch in other issues or solved, I mark this as resolved.
Thank you again for your help, I will continue working with odata2ts with interest !
