### ISSUE TITLE
V2: Expanded Collections with Extra Result Wrapping

### ISSUE THREAD

**Issue by texttechne** [odata2ts/odata2ts#125]
In some V2 services, at least in the SAP universe, expanded collection properties responses are represented by a JSON array encapsulated in an addtional results object (@involture brought this up in #119).

Borrowing from the Trippin service, for a `Person` with selected and expanded `Trip`s it would look like:
```json
{
  "d": {
    "trips": {
      "results": [
        ...
      ]
    } 
  }
}
```
Instead of being the results array itself, `trips` is an object with the `results` property which holds the results array. 

The spec actually has an example for that: [JSON-Format, chap. 9](https://www.odata.org/documentation/odata-version-2-0/json-format/). Hence, it seems to be plainly wrong, as @involture pointed out. It's nevertheless an use case if some SAP services behave this way.

## Solution Approach
First and foremost we need a workaround which removes the extra wrapping, so that the generated types are correct.

If useful, provide an additional service setting which respects this extra wrapping.
Setting name: `v2ExtraResultsWrapping`
Setting type: boolean (default: false)

**Comment by texttechne** [comment]
@Involture is the description of the behaviour correct? Can you confirm the response structure?

**Comment by Involture** [comment]
It is correct indeed !

**Comment by texttechne** [comment]
Fixed in `@odata2ts/odata-query-objects@0.17.0` or: 
* `@odata2ts/odata-query-builder@0.15.6`
* `@odata2ts/odata-service@0.13.5`

@Involture it would be really great if you can confirm this with the usage of a live example. Tests are in place, but nothing beats a real live test.

**Comment by Involture** [comment]
After a quick test on one query, it seems to work as expected. I will reopen this issue if I find a bug in the following days.

**Comment by HappyHepo** [comment]
As someone working with OData services from the SAP universe and using the "model" mode just for type safety, I need the aforementioned setting for the extra results wrapping.
Please consider implementing it.
