### ISSUE TITLE
Add support for System Query Option $search

### ISSUE THREAD

**Issue by gregorwolf** [odata2ts/odata2ts#13]
The OData V4 specification defines the [System Query Option $search](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752364). As OData V4 Services implemented with the [SAP Cloud Application Programming Model](https://cap.cloud.sap/docs/) [support the $search Query Options](https://cap.cloud.sap/docs/advanced/odata#overview) it would great to also support it in this client.

**Comment by texttechne** [comment]
The ODataUriBuilder (V4 only) now supports the concept of searching for a single term or a single phrase. It has the method `search(term: string)` which translates to: 
* `$search=term`
* `$search="a whole phrase"`

@gregorwolf Please verify that you're able to handle a single term and a single phrase with CAP.

The spec also allows for using `NOT`, `AND` and `OR` as well as grouping. This is not implemented.

@gregorwolf Please also check, if you're able to handle complex queries with CAP:
* `$search=blue OR (green AND "a whole phrase")`
* ...

From the spec:
```
Terms can be any single word to be matched within the expression.

Terms enclosed in double-quotes comprise a phrase.

Each individual term or phrase comprises a Boolean expression that returns true if the term or phrase is matched, otherwise false. The semantics of what is considered a match is dependent upon the service.

Expressions enclosed in parenthesis comprise a group expression.

The search expression can contain any number of terms, phrases, or group expressions, along with the case-sensitive keywords NOT, AND, and OR, evaluated in that order. 
```
