### ISSUE TITLE
Source maps in distributed packages

### ISSUE THREAD

**Issue by Involture** [odata2ts/odata2ts#130]
**Problem**
All the packages of @odata2ts group seem to be published with source maps files referencing typescript sources. Once distributed, these source maps points to non-existant files. It can raise some warnings in some build systems.

**Solution**
One of the three following options would work
- Do not distribute source maps with the packages
- Inline the typescript sources in the sourcemaps files using the `inlineSources` tsc option
- Distribute the `src` directory containing the typescript files with the packages

**Comment by texttechne** [comment]
Great Catch!

I've thought I would go without source maps then, because no one needs this for a deployed lib, right?

Then I figured out, that I actually need them myself for debugging purposes.
Furthermore, when going with the `inlineSources` approach, then I'm only bloating up the `.js.map` files, not the library code consumed by users.

@Involture Any thoughts from your side?

**Comment by Involture** [comment]
From the discussions I read, I'm leaning towards no source at all : 
-> I use sources for developpement too. For distribution I use a separate build script with the exact same options but with source maps disabled and another output directory. 
-> distributing ts files is the second best option. I think it is the only way for the user to debug an error originating from the library. However, a good library shouldn't have bugs. Errors should be self explanatory and provide guidance on how to fix them. (I am not saying I am capable of writing such a library)
-> However, source maps with inlined source do not cause much harm. Their only disadvantage is taking up bandwith an npmjs storage space, as well as confusing people who never heard about .map files.

So … yeah, the debate is still not settled and I myself could very well change my mind in the future. Whatever you decide is good

**Comment by Involture** [comment]
I also just realized the library consists of several package and you may have them published and installed from npmjs in other packages. Going with the "no source" may complicates things for you

**Comment by texttechne** [comment]
My understanding is, that `inlineSource=true` will also enable people to debug the library. But in any case and as you point out, changing to that option won't do much harm.

Changed to `inlineSource=true` for the following packages:
- @odata2ts/odata-query-builder@0.15.6
 - @odata2ts/odata-query-objects@0.17.0
 - @odata2ts/odata-service@0.13.5
 - @odata2ts/odata2ts@0.19.0

**Comment by Involture** [comment]
Can you do the same for odata-core, axios-odata-client and converter-runtime ?

**Comment by texttechne** [comment]
yeah, I have it in mind. I wanted to do that as part of the documentation migration, because I need to do some changes in the repo (the configuration setting is part of the root => no change for each module is auto-detected).

So do you need this fast or can you wait til the weekend / next week?

**Comment by Involture** [comment]
I can definitly wait for as long as needed. It's only a minor quality of life thing to make some warnings disappear

**Comment by texttechne** [comment]
Finally released a README rewrite for all modules. Now all modules have `inlineSource=true`.

Please check and close issue if successful.
