### ISSUE TITLE
[Enhancement][AxiosOdataClient]Better error reporting

### ISSUE THREAD

**Issue by Involture** [odata2ts/odata2ts#134]
I have been using the provided axiosOdataClient as a client for odata2ts.
I think it would be a good idea to keep the original axios error. It is necessary for accessing the request data for example.

In general, making use of the new standard `cause` field (as of ES 2022) of the Error interface seems to be a good idea.
However the target of AxiosODataClient seems to be ES 2016 (sensible choice). A polyfill lib could be added such as [this one](https://github.com/es-shims/error-cause#readme), or a `cause` field could be added to the AxiosOdataClientError class.

It would make the type `RequestError` redondant

Also my understanding is that a proper name for the error is better for error reporting.

My suggestion for modifying the convertError code
*DISCLAMER*: it did not check/test this code, its merely an idea 
```typescript
export class AxiosODataClientError extends Error {
  name: "AxiosODataClientError"
  isAxiosOdataClientError: true
  constructor(msg: string, options?: {cause?: any}): {
    super(msg, options)
  }
}

private convertError(error: Error): Error {
  if ((error as AxiosError).isAxiosError) {
    const axiosError: AxiosError = error as AxiosError;

    const message = this.getErrorMessage(axiosError);

    if (message) {
      return new AxiosODataClientError("OData server error: " + message, { cause: error })
    } else {
      return new AxiosODataClientError("Axios error", { cause: error })
    }
  }
  return new AxiosODataClientError("Internal Error", { cause: error });
}
```

I am not sure I understand error management good practices properly, but I am sure it would be nice to access the resquest and response fields of the AxiosError

@texttechne What do you think ?

**Comment by texttechne** [comment]
Hi @Involture,
good call on the exception handler. As `axios-odata-client` was the only odata-client it was hard to get the API right. So I didn't spend too much thought on that.
Recently, I've added `jquery-odata-client` as first step to integrate `odata2ts` into UI5. So now it starts making sense to revisit that part.

I definitely like the idea to wrap the original error into the `cause` field. 

You're more than welcome to create a PR.

**Comment by Involture** [comment]
I will get to work and create a PR, do you have code guidelines that I should follow somewhere ?

**Comment by texttechne** [comment]
Sounds great, really appreciated!

I haven't formalized any code guidelines, but I would guess that you'll find your way and see what kind of conventions I use. Otherwise just ask in case of doubt. The only requirement should be code formatting with `prettier`...

**Comment by Involture** [comment]
Linked PR : #139 
I dont think I can link the pull request to the issue myself. Or at least I didn't find how.

**Comment by texttechne** [comment]
Released with
 - `@odata2ts/axios-odata-client@0.6.0`
 - `@odata2ts/jquery-odata-client@0.2.0`

And contribution guidelines have also been created as by-product of this.

Big thanks to @Involture!
