### ISSUE TITLE
Generator docs should clearly state that date types are not parsed without converters

### ISSUE THREAD

**Issue by manuelseeger** [odata2ts/odata2ts#164]
In the docs, converters are their own chapter. Under configuration there is a link to the converter chapter and a mention on where the converter configuration should go. However, it doesn't say WHY one would want a converter. 

Converters, or possibly "emitted TS types" or something like that should be it's own top level chapter under 
https://odata2ts.github.io/docs/generator/configuration

The chapter should state clearly that per default, date types are not parsed and generated string types, and link to the converter chapter for a solution to date parsing.

**Comment by texttechne** [comment]
Thanks for creating the issue!

Here is the section: [Types and Converters](https://odata2ts.github.io/docs/generator/configuration#types-and-converters)

Is this what you envisioned?

**Comment by manuelseeger** [comment]
Looks good!
