### ISSUE TITLE
Parsing metadata with Singleton entity is not possible

### ISSUE THREAD

**Issue by heimwege** [odata2ts/odata2ts#176]
Parsing a metadata document containing a [singleton entity](http://docs.oasis-open.org/odata/odata/v4.0/cos01/part3-csdl/odata-v4.0-cos01-part3-csdl.html#_Toc372793988) results in the error message `Key property is missing from Entity "MyEntity"`.

Sample:

```
[...]
<Singleton Name="MyEntity" Type="MyService.MyEntity"/>
[...]
<EntityType Name="MyEntity">
    <Property Name="myProperty" Type="Edm.Boolean" DefaultValue="false"/>
</EntityType>
[...]
```

**Comment by texttechne** [comment]
Hi @heimwege,

Singletons are supported as demonstrated by the Trippin example.

The error message is to be taken literally here: You defined an `EntityType` without keys. This is not conform with the OData spec. You could use `ComplexType` here.... but it's probably just an example...

**Comment by heimwege** [comment]
Hey @texttechne,

Thanks for the quick reply 👍 As the metadata in my case is generated by the [SAP Cloud Application Programming Model](https://cap.cloud.sap/docs/) I'll get in touch with them.

Cheers
Dominik

**Comment by heimwege** [comment]
Can confirm that it works if a key if provided. I've fallen into the "can be omitted" trap in the [CAPire documentation](https://cap.cloud.sap/docs/advanced/odata#singletons) 🙈 Thanks for pointing me into the right direction @texttechne

**Comment by heimwege** [comment]
Hey @texttechne,

I just found out while discussing with the CAP guys (I wanted to trigger an adjustment of the above described misleading line in capire) that singletons do not require a key as of [OData 4.01 Spec](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_Key):

_In OData 4.01 responses entity types used for singletons or single-valued navigation properties do not require a key. In OData 4.0 responses entity types used for singletons or single-valued navigation properties MUST have a key defined._

So I just wanted to let you know that according to OData 4.01 the initially described issue seems to be a bug in odata2ts. Nevertheless in my case everything works fine because I simply added a key to my singleton.

**Comment by texttechne** [comment]
Hi @heimwege,

thanks for pointing that out.
I see what I can do there.

**Comment by texttechne** [comment]
Hi @heimwege,

keyless EntityTypes are now supported with release `0.33.0` of the generator.
So your original example should work now. 

Thanks for bringing that detail to light, allowed me to see the bigger picture. 
odata2ts shouldn't check for validity but cope with the information given: in this case certain stuff won't be generated if no keys are provided for an EntityType.
