### ISSUE TITLE
after update to 0.27.0 Edm.Decimal as string

### ISSUE THREAD

**Issue by bi-tm** [odata2ts/odata2ts#192]
Hello Hubert,
after update from 0.22.0 to 0.27.0 the type mapping is changed. 

previously the type _Edm.decimal_ was implemented as _number_ in the typescript. in the new version it now becomes a _string_.

for testing purposes the repository [https://github.com/bi-tm/odata2ts-test](https://github.com/bi-tm/odata2ts-test) can be used, see entity _HandlingUnit_ in file _odata/ZppBdeSrvModel.ts_.
in branch _main_ with v0.27.0 : the property _qty_ is typed as string [.../main/odata/ZppBdeSrvModel.ts](https://github.com/bi-tm/odata2ts-test/blob/main/odata/ZppBdeSrvModel.ts)
in branch _old_ with v0.22.0 : the property _qty_ is typed as number. [.../old/odata/ZppBdeSrvModel.ts](https://github.com/bi-tm/odata2ts-test/blob/old/odata/ZppBdeSrvModel.ts)

kindly
Torsten

**Comment by texttechne** [comment]
Hi @bi-tm,

yeah that was a breaking change in the v2-to-v4-converter: [here's the commit](https://github.com/odata2ts/converter/commit/55645041a4a887297e3cffa0ccdf20751c1da230)

Does it really make sense to convert `Edm.Decimal` to `number`? You could have a potential precision loss...

**Comment by texttechne** [comment]
Ok, I've introduced this breaking change in the wake of developing the `converter-ui5-v2`: The V2 OData model of SAP doesn't convert `Edm.Int64` or `Edm.Decimal`. I think I was a little helpless there...

I've found a better solution now:
*  by default, the `converter-v2-to-v4` will transform both types to `number`
  * this is how V4 behaves anyway
* I've added a `bigNumberNoopConverter` which overrides this behaviour and leaves the types to be `string`
  * this is used by the `converter-ui5-v2`

Please update `@odata2ts/converter-v2-to-v4` to version `0.3.0`.

**Comment by texttechne** [comment]
@bi-tm if this works for you, then please close the ticket.

And the question from my side remains: Don't you have any concerns regarding precision loss? Or is this data type mapping just a little bit imprecise (like `Edm.Double` would be already enough but it's mapped to `Edm.Decimal` anyway)?
