### ISSUE TITLE
Prettier@2.8.8 dependency on @odata2ts/odata2ts

### ISSUE THREAD

**Issue by lpmusicon** [odata2ts/odata2ts#202]
Hello,
I've noticed that odata2ts package uses @prettier/plugin-xml 3.1.1, but it has prettier version 2.8.8.
Do you mind updating all prettier deps to ^3.x?
```
├─┬ @odata2ts/odata2ts 0.28.0
│ └─┬ @prettier/plugin-xml 3.1.1
│   └── ✕ unmet peer prettier@^3.0.0: found 2.8.8
```

**Comment by texttechne** [comment]
Hi @lpmusicon,

good catch, thanks! I'll fix it as soon as I can.

**Comment by texttechne** [comment]
Hi @lpmusicon,

seemed to be an easy fix, but it is not. `prettier@3.x` is build as ESM, which works but ruins the jest tests.

After investing some time, I've decided to downgrade `@pretter/plugin-xml` to version `2.2.0`. At least both versions are aligned now. Install version `0.29.0` of `@odata2ts/odata2ts` and `0.17.0` of `@odata2ts/odata-service`.

Does this work for you for the time being?

**Comment by lpmusicon** [comment]
Hi @texttechne,
It's alright, just wanted to point that out :) Certainly does work for me, thanks
