### ISSUE TITLE
Error/Bug client.retrieveBigNumbersAsString do not exist

### ISSUE THREAD

**Issue by lfhenrl** [odata2ts/odata2ts#203]
Hi 
I am new to this library and is very impressed. 
But I think there is a bug.
I Got this error: ODataService.ts:11 Uncaught (in promise) TypeError: this.client.retrieveBigNumbersAsString is not a function

I had to remove this line: client.retrieveBigNumbersAsString(bigNumbersAsString);
 in ServicebaseV4 and OdataService.
to get it working.

**Comment by texttechne** [comment]
Hi @lfhenrl,

ahhh damn. I've already released the changes to the http-client repo while the changes you've mentioned (main repo) are committed but not released 😅: [Here they are](https://github.com/odata2ts/odata2ts/commit/0ede9f2344e2c93a02d27a21c82b5d0a33c93feb#diff-2704cef960eebc70be391f8071d11b305550647caa0424095b80bbd54a464f5aL11)

So I need to do a release. Alternatively, you would need to downgrade the http client (axios or fetch): [See the latest releases](https://github.com/odata2ts/http-client/releases) and choose one from before that. But I will release soon probably.

**Comment by texttechne** [comment]
Hi @lfhenrl,

has been released with version `0.29.0` of `@odata2ts/odata2ts` and `0.17.0` of `@odata2ts/odata-service`.

If it works for you, then please close this ticket.

And thanks for bringing this up!

**Comment by lfhenrl** [comment]
Hi Hubert
Its working after the update, Thanks I will close the ticket.
I am very impressed with the quality of the code and the documentation, many thanks for the great work that went into creating this.
I have 2 suggestions.

1.	Emulation of In Operator. Could it be an Idia to make this as an option in the configuration, so if you have an Odata service that can handle this standard can use the native.

2.	In the attached bundleAnalyze.png I can se the bundle contains both V2 and V4 modules could it be possible to only use V2 or V4. I do not know if this is possible maybe they depend on each other.
 
![bundleAnalyze](https://github.com/odata2ts/odata2ts/assets/10332372/7608f054-a4cc-4ee2-8814-03bf2ab5893e)

**Comment by texttechne** [comment]
Hi @lfhenrl,

thanks for the compliment, much appreciated!

Both of your suggestions make sense and also have crossed my mind a couple of times.
Feel free to create new issues for them!
