### ISSUE TITLE
[Enhancement suggestion] allow to add addition get parameter like sap-client

### ISSUE THREAD

**Issue by p-mathias** [odata2ts/odata2ts#208]
I hope i didn't overlooked but i didn't find a way,
to define a addition url parameter like sap-client to define which client i want to talk.
goal would be ``http://server.com/service?sap-client=200`` as service call

**Comment by texttechne** [comment]
Hi @p-mathias,
query params belong to the responsibility of the used HTTP client.
I would imagine that you're using the `JqueryHttpClient` as it is about SAP.

For axios and fetch there are options readily available which can be set on a global level when intializing the HTTP client.
Axios example:
```ts
new AxiosHttpClient({params: {"sap-client": "200"})
```

I'm astonished to see that it's not that easy regarding jQuery. It looks like you can use [the prefilter option](https://api.jquery.com/jQuery.ajaxPrefilter/) for that use case. Then along these lines:
```
$.ajaxPrefilter(function( options ) {
    options.url = options.url + "?sap-client=200";
  }
});
```
Probably you would need to do a bit more logic here => when querying, then you need to check if the "?" becomes a "&"...

I'll ponder a bit, if this can be easily built-into the jqueryHttpClient.

If you have any suggestions regarding improvements of the docs in this respect...

**Comment by p-mathias** [comment]
Well jquery is fare away from being in scope for me,
atm i try my luck with fetch api,
but doesn't got working solution done.

**Comment by p-mathias** [comment]
some expierence i woud like to share;
i had to setup local proxy for cors stuff
since i already use vite for bundling is also use his proxy
vite.config.ts:
```
    server: {
      proxy: {
        '/endPoint': { // localhost:5173/endPoint
          target: 'https://company_server.com/path_to_endPoint', // https://abap_server.com/sap/opu/odata/sap/
          changeOrigin: true,
          secure: false,

          configure: (proxy, options) => {
            const username = process.env.VITE_ABAP_USER
            const password = process.env.VITE_ABAP_PASSWORD
            options.auth = `${username}:${password}`
          }
        }
      }
    },
```

in .env i define my abap username and pw
```
VITE_ABAP_USER="USERNAME"
VITE_ABAP_PASSWORD="Secret"
```
to get env in vite config
loadEnv needs to be imported
process.env needs to be loaded: ``   process.env = { ...process.env, ...loadEnv(mode, process.cwd()) }``

since i didn't like to had the url end point in my code i also use the odata2ts.config.ts to read the url to my service:
```
  services: {
    endPoint: {
      sourceUrl: import.meta.env.PROD
        ? 'https://abap_server.com/sap/opu/odata/sap/endPoint'
        : 'http://localhost:5173/endPoint',
      source: 'resource/endPoint.xml',
      output: 'build/endPoint'
    },
```
so when i run in local dev the proxy is taken on build/preview the real server endPoint is used.

about adding parameter to the url:
i created a own fetch class and extend the get/put methode:
```ts
class myFetch extends FetchClient {
  constructor(...args) {
    super(args)
  } 
  public post(url, data, requestConfig, additionalHeaders) {
    url = url + '?sap-client=200'
    return super.post(url, data, requestConfig, additionalHeaders)
  }

  public get(url, requestConfig, additionalHeaders) {
    url = url + '?sap-client=200'
    return super.get(url, requestConfig, additionalHeaders)
  }
}
```
this my journey atm

**Comment by texttechne** [comment]
Hi p-mathias,
ah ok, so this is also missing in the fetch client. 
I'll add this option to both clients then as constructor param (see Axios example).

**Comment by texttechne** [comment]
Hi @p-mathias,

I've added appropriate options for the fetch and jquery http client.
For fetch it would like:
```ts
new FetchClient({params: {"sap-client": "200"}}); // actually doesn't matter if you use "200" or 200 as number
```

Released with  `@odata2ts/http-client-fetch` version `0.5.0`.

Please try it out and close this issue if it works.

**Comment by p-mathias** [comment]
okay i will do it

**Comment by p-mathias** [comment]
0.5 doesn't got released so i can't test this: https://www.npmjs.com/package/@odata2ts/http-client-fetch

**Comment by p-mathias** [comment]
works fine
