### ISSUE TITLE
CSRF Token get not fetched (with fetch client)

### ISSUE THREAD

**Issue by p-mathias** [odata2ts/odata2ts#212]
When i try to change the data by post i get the error message from the abap server,
that crsf validation failed.

Based on the doc: https://odata2ts.github.io/docs/odata-client/http-client/fetch#automatic-csrf-token-handling
is this my setup (i used fetch client)
```
const httpClient = new myFetch(// standard config => irrelevant right now
undefined,// ClientOptions
{
    useCsrfProtection: true,
    csrfTokenFetchUrl: "/sap/opu/odata/sap/SERVICES_SRV"
});
```
which doesn't solve the issue.

I looked in the blog post: https://blogs.sap.com/2021/06/04/how-does-csrf-token-work-sap-gateway/
tldr it say you need to do first a get request to get the csrf token and then provide it with the post call.

Based on this information i looked at the network traffic my web application and
notice that a post request get send with x-csrf-token: required

what i missing is get request in short hand before or in startup of my app to get by a get request the csrf token.

Or had i to look somewhere else?

**Comment by texttechne** [comment]
Hi @p-mathias,

I've taken a look at my projects. There's one quirk here obviously. You have to use  a final "/" for your `csrfTokenFetchUrl`.
So in your example: `"/sap/opu/odata/sap/SERVICES_SRV/"`.

**Comment by p-mathias** [comment]
okay i pointed the issue out,
my custom class for fetch (which add the sap-client information to the call) is the issue,
now i had to look which endpoint provide me an csrf token

**Comment by texttechne** [comment]
Ah cool.

I usually use the main service path, like in your example: `/sap/opu/odata/sap/SERVICES_SRV/`. 
Actually any valid service URL will do, but this one is by design not that a big request....

**Comment by p-mathias** [comment]
well i got somekind of long message back now,
i guess somekind of error from my side,
but i had to look in another day into it.

my code look like this atm:
```
class myFetch extends FetchClient {
  constructor(config, ClientOptions) {
    super(config, ClientOptions)
  }
  /**
   * post
   */
  public post(url, data, requestConfig, additionalHeaders) {
    url = url + '?sap-client=200'
    return super.post(url, data, requestConfig, additionalHeaders)
  }

  public get(url, requestConfig, additionalHeaders) {
    url = url + '?sap-client=200'
    return super.get(url, requestConfig, additionalHeaders)
  }
}


const httpClient = new myFetch( // standard config => irrelevant right now
  undefined,
  // ClientOptions
  {
    useCsrfProtection: true,
    csrfTokenFetchUrl: import.meta.env.PROD
      ? 'https://prod.com/sap/opu/odata/sap/SERVICES_SRV/'
      : 'http://localhost:5173/SERVICES_SRV/'
  }
)
```

**Comment by texttechne** [comment]
Ok, since additional global query params are now supported (#208), you don't need your custom implementation anymore.

If you need further assitance, then post the error message ;-)

**Comment by p-mathias** [comment]
issue cause by my self
