### ISSUE TITLE
auto CSRF function get confused by body

### ISSUE THREAD

**Issue by p-mathias** [odata2ts/odata2ts#213]
Last week we got to the state the auto csrf function is kicking in,
when csrf is needed by post request.

i notice that the post request doesn't get send since then,
while checking today what could be the issue,
i notice an error in the console:
```
 Retrieving JSON body from OData response failed: Unexpected token '<', "<?xml vers"... is not valid JSON
 ```
 This error meesage sense and not sense in the same time,
the return of the get call (where csrf token is collected) a response from the server,
which is in xml.
But two things make this thing, i guess to an issue/bug:
- it's doesn't define that the format should be in json in request header -> why expect that the response body is in json?
- we don't care about the the response body since in the response header is the x-csrf-token maintained and this all we needed

Please had in mind this i an oDataV2 interface

place where the error hapen:
https://github.com/odata2ts/http-client/blob/ed6b01821c2dc161f05144e3b4d8f8d899f954ae/packages/fetch/src/FetchClient.ts#L98

**Comment by texttechne** [comment]
Hi @p-mathias,
damn that's particular to the fetch client.... For now, as workaround: Append `?$format=json` to the `csrfTokenFetchUrl`.

**Comment by p-mathias** [comment]
fixed the issue,
should i close the issue?

**Comment by texttechne** [comment]
No, please leave it open. I still need to fix the underlying issue.

**Comment by texttechne** [comment]
Hi @p-mathias,

with the newest version of the fetch client you can remove the format parameter.
Tested and works.

**Comment by p-mathias** [comment]
with the fixed version ``?$format=json`` is not needed any more
