### ISSUE TITLE
Post over fetch doesn't work, maybe content type wrong

### ISSUE THREAD

**Issue by p-mathias** [odata2ts/odata2ts#214]
Since we solved that the csrf now,
i try to get post working.
I get a 415 https://answers.sap.com/questions/12902174/odata-service-error-message-unsupported-media-type.html
so i looked at the content-type in the header of the request and here is text/plain,
which should be application/json i guess.
![image](https://github.com/odata2ts/odata2ts/assets/108936601/c35e5efb-7bca-4cee-a166-05d28bb6d6b8)
the body of my post is a json ``{"something":false}``

**Comment by texttechne** [comment]
Hi @p-mathias,

the http-client implementation threw away other headers as soon as CSRF was activated. This is fixed now.

Install the newest versions:
* `@odata2ts/http-client-fetch` version `0.6.2`
* `@odata2ts/odata-service` version `0.17.1`
* `@odata2ts/odata2ts` version `0.29.1`

Please test and close the issue if this works for you.

**Comment by p-mathias** [comment]
wtih the new version post works now.
