### ISSUE TITLE
[Usage Question] Addition of query parameters

### ISSUE THREAD

**Issue by Nadalt15668** [odata2ts/odata2ts#240]
How can I add additional query parameters?
For example, with SAP I would like to specify the language using the 'sap-language' query parameter, however I couldn't find any information regarding the addition of such query parameters using the query builder.

From what I understand the only query parameters I can add using the query builder are the ones available through methods of the builder.

**Comment by texttechne** [comment]
Hi @Nadalt15668,

you can specify global query params like "sap-language" when initializing the client. Let's assume you use the FetchClient:

```ts
const odataClient = new FetchClient(
    { params: {"sap-language": "de" },  // here you have the full requestConfig object to set query params & headers
    { useCsrfProtection: true,  odataPath + "/" }, // in here goes the configuration for auto CSRF token handling
  });
```

Seems I haven't documented that...

**Comment by Nadalt15668** [comment]
Awesome I could use that but is there any of doing it per query and not globally using the client?

**Comment by Nadalt15668** [comment]
Oh I've looked through it so many times and couldn't find anything 🫠Thanks 🙏

**Comment by texttechne** [comment]
Yeah, I need to overhaul the docs... quite some work....
