### ISSUE TITLE
[Bug Report] TypeScript: `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by hakimio** [odata2ts/odata2ts#243]
Firs of all, would like to say that I really love the `odata2ts` API design. It has really great DX. Extremely nice to use.

Unfortunately, it doesn't seem to be "production ready".

### Issues
- Both `TypeScript` when using `emitMode: EmitModes.ts` and `ts-morph` when using `emitMode: EmitModes.js_dts` throw `Maximum call stack size exceeded` errors when running the app with TS & generating code with `ts-morph`.
TS error looks like this:
```
RangeError: Maximum call stack size exceeded
    at isRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:63211:27)
    at eachTypeRelatedToType (C:\my-app\node_modules\typescript\lib\typescript.js:63650:30)
    at unionOrIntersectionRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:63487:176)
    at structuredTypeRelatedToWorker (C:\my-app\node_modules\typescript\lib\typescript.js:64076:25)
    at structuredTypeRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:63918:23)
    at recursiveTypeRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:63868:21)
    at isRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:63308:124)
    at isPropertySymbolTypeRelated (C:\my-app\node_modules\typescript\lib\typescript.js:64656:16)
    at propertyRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:64696:25)
    at propertiesRelatedTo (C:\my-app\node_modules\typescript\lib\typescript.js:64908:31)
```
`ts-morph` error is almost the same:
```
RangeError: Maximum call stack size exceeded
    at compareSignaturesRelated (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:61142:38)
    at signatureRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:63612:16)
    at signaturesRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:63514:29)
    at structuredTypeRelatedToWorker (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:62982:26)
    at structuredTypeRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:62439:23)
    at recursiveTypeRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:62409:21)
    at isRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:61862:124)
    at isPropertySymbolTypeRelated (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:63178:16)
    at propertyRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:63233:25)
    at propertiesRelatedTo (C:\my-app\node_modules\@ts-morph\common\dist\typescript.js:63450:31)
```
- It doesn't deal correctly with namespaces and puts everything in one namespace which results in duplicates/conflicts.
- Probably related to namespace issue it generates invalid code which looks like the following:
```ts
export class webapi.ModelsService<ClientType extends ODataHttpClient> extends ODataService<ClientType> {}
```
Obviously `webapi.ModelsService` is not a valid class name.

Example `odata2ts` service usage:
```ts
import {qClientAlias} from './types/Qwebapi.Models';
import {ClientAliasCollectionService} from './types/webapi.ModelsService';
import {FetchClient} from '@odata2ts/http-client-fetch';


async function myTestFunction() {
    const filter = qClientAlias.Contract.any(
        contract => contract.Status.eq('Active')
            .and(contract.ProductPackage_Id.isNotNull())
            .and(contract.Parent_Id.isNull())
    );

    const httpClient = new FetchClient();
    const clientAliasService = new ClientAliasCollectionService(httpClient, process.env.OLD_CRM_ENDPOINT, 'ClientAlias');
    const response = await clientAliasService.query(
        (query, clientAlias) => query.filter(filter)
            .expand('Country', 'Client', 'Contract')
            .orderBy(clientAlias.Id.desc())
            .top(10)
    );

    console.log(JSON.stringify(response.data.value));
}
```

### Reproduction

I have attached two reproductions: slightly simplified just for `Maximum call stack size exceeded` and the other containing the rest of the issues. The simplified version also contains the config. The `all-errors` one also has a slightly more complex odata edmx schema.

[odata2ts-simplified-max-call-stack-exceeded-reproduction.zip](https://github.com/odata2ts/odata2ts/files/14191477/odata2ts-simplified-max-call-stack-exceeded-reproduction.zip)
[odata2ts-all-errors.zip](https://github.com/odata2ts/odata2ts/files/14191679/odata2ts-all-errors.zip)

**Comment by hakimio** [comment]
One more minor issue: the generator says `Emitting 3 TS files` even when it emits only one (`mode: Modes.models`).

**Comment by texttechne** [comment]
Hi @hakimio,

actually it is used in production. However, the main audience is either coming from SAP or Microsoft. Both groups have quite disparate requirements and use different features... 

Regarding your issues:
* namespaces: this issue has already been raised & I've developed a solution where name clashes are resolved automatically, but still need to test more & find the time to release it: see #222
* the call stack issue should be due to a really huge EDMX & the app running out of memory
  * given that this issue is not due to the namespace conflict and some circular stuff
  * I need to take a look there to identify the performance bottle necks

**Comment by hakimio** [comment]
Hi Hubert,

to be honest, I haven't thought that the issue might be with the size of the metadata and just assumed that it's some circular/recursive dependency issue, but now it seems very plausible that the issue is caused by the size. If you do find out that it's just the size at fault and there isn't anything you can optimize to reduce the memory usage, feel free to close this bug report.

You can find the original unmodified metadata.xml in the [odata2ts-all-errors.zip](https://github.com/odata2ts/odata2ts/files/14191679/odata2ts-all-errors.zip) file. It's generated by MS ASP.NET odata project.

Concerning the namespace issue, I'm curious how do you plan to solve it: are you going to use actual TS namespaces or separate the model definition into multiple files or sth else entirely?

**Comment by texttechne** [comment]
Hi @hakimio,

I'll try to find the time this weekend to analyse the problem but no promises...

Solution approach regarding namespaces: For now, I would stick with generating exactly one service. I get headaches when thinking of generating separate services based on namespaces 😅.

So, I've already build a simple detection and renaming mechanism for duplicate names. Furthermore, you'll get the option to rename stuff based on fully qualified names, so you stay in control of the generated names.
See #239 & #238

**Comment by texttechne** [comment]
Hi @hakimio,

finally found the time to release the automatic name clash resolution stuff.
And with this I can run both of your examples without any error. So you were right, I guess: circular dependency by virtue of not handling namespaces correctly.

For your example "all-errors" it shows the following now:
```
Duplicate name: Invoice - Fully Qualified Names: webapi.Models.Invoice, webapi.Helpers.Fenerum.Invoice (renamed to: Invoice2)
Duplicate name: InvoiceLine - Fully Qualified Names: webapi.Models.InvoiceLine, webapi.Helpers.Fenerum.InvoiceLine (renamed to: InvoiceLine2)
Duplicate name: ODataBatchContent - Fully Qualified Names: System.Web.Http.OData.Batch.ODataBatchContent, System.Web.OData.Batch.ODataBatchContent (renamed to: ODataBatchContent2)
Duplicate name: ODataBatchResponseItem - Fully Qualified Names: System.Web.Http.OData.Batch.ODataBatchResponseItem, System.Web.OData.Batch.ODataBatchResponseItem (renamed to: ODataBatchResponseItem2)
Duplicate name: OperationResponseItem - Fully Qualified Names: System.Web.Http.OData.Batch.OperationResponseItem, System.Web.OData.Batch.OperationResponseItem (renamed to: OperationResponseItem2)
Duplicate name: ChangeSetResponseItem - Fully Qualified Names: System.Web.Http.OData.Batch.ChangeSetResponseItem, System.Web.OData.Batch.ChangeSetResponseItem (renamed to: ChangeSetResponseItem2)
Duplicate name: ClientValues - Fully Qualified Names: webapi.ComplexTypes.ClientValues, Statistic_action.ClientValues (renamed to: ClientValues2)
Duplicate name: MissingInvoice - Fully Qualified Names: Subscription_action.MissingInvoice, Contract_action.MissingInvoice (renamed to: MissingInvoice2)
Duplicate name: CheckLink - Fully Qualified Names: Lead_action.CheckLink, Contract_action.CheckLink (renamed to: CheckLink2), ClientAccount_action.CheckLink (renamed to: CheckLink3)
Duplicate name: GetBudget - Fully Qualified Names: Lead_action.GetBudget, Contract_action.GetBudget (renamed to: GetBudget2)
Duplicate name: SendLink - Fully Qualified Names: Lead_action.SendLink, Contract_action.SendLink (renamed to: SendLink2)
Duplicate name: RemoveLink - Fully Qualified Names: Lead_action.RemoveLink, Contract_action.RemoveLink (renamed to: RemoveLink2)
Duplicate name: Payments - Fully Qualified Names: webapi.ComplexTypes.Payments, Statistic_action.Payments (renamed to: Payments2)
Duplicate name: ContractExpectedPayments - Fully Qualified Names: webapi.Helpers.Stats.ContractExpectedPayments, Statistic_action.ContractExpectedPayments (renamed to: ContractExpectedPayments2)
Duplicate name: List - Fully Qualified Names: InvoiceEvent_action.List, PlanTerm_action.List (renamed to: List2)
Duplicate name: GetByUuid - Fully Qualified Names: InvoiceEvent_action.GetByUuid, PlanTerm_action.GetByUuid (renamed to: GetByUuid2)
Duplicate name: SLAData - Fully Qualified Names: webapi.ComplexTypes.SLAData, Public_action.SLAData (renamed to: SLAData2)
Duplicate name: CSAT - Fully Qualified Names: webapi.ComplexTypes.CSAT, Public_action.CSAT (renamed to: CSAT2)
Duplicate name: Stats - Fully Qualified Names: Lead_action.Stats, SellerGoal_action.Stats (renamed to: Stats2), TimeRegistration_action.Stats (renamed to: Stats3)
Duplicate name: Confirm - Fully Qualified Names: EmployeeInfo_action.Confirm, Order_action.Confirm (renamed to: Confirm2), InformationScheme_action.Confirm (renamed to: Confirm3)
Duplicate name: Approve - Fully Qualified Names: ChangeRequest_action.Approve, Order_action.Approve (renamed to: Approve2), InformationScheme_action.Approve (renamed to: Approve3)
Duplicate name: NewTask - Fully Qualified Names: TaskList_action.NewTask, TaskListTemplate_action.NewTask (renamed to: NewTask2)
Duplicate name: Assign - Fully Qualified Names: Lead_action.Assign, Contract_action.Assign (renamed to: Assign2)
Duplicate name: Move - Fully Qualified Names: Lead_action.Move, Contract_action.Move (renamed to: Move2), ClientAlias_action.Move (renamed to: Move3)
Duplicate name: SellerIndex - Fully Qualified Names: webapi.ComplexTypes.SellerIndex, Statistic_action.SellerIndex (renamed to: SellerIndex2)
Duplicate name: AddProduct - Fully Qualified Names: Draft_action.AddProduct, ProductPackage_action.AddProduct (renamed to: AddProduct2)
Duplicate name: Reject - Fully Qualified Names: ChangeRequest_action.Reject, InformationScheme_action.Reject (renamed to: Reject2)
Duplicate name: KPIData - Fully Qualified Names: webapi.ComplexTypes.KPIData, ClientAlias_action.KPIData (renamed to: KPIData2)
Duplicate name: ForItem - Fully Qualified Names: Comment_action.ForItem, TimeVault_action.ForItem (renamed to: ForItem2)
```

You can rename everything to your liking via option "byTypeAndName":
```
const config: ConfigFileOptions = {
  // ...
  services: {  
    manualRenaming: {
      // ...
      byTypeAndName: [
        // This solves the problem of duplicate names (same name in different namespaces)
        // by renaming one of those entities, which must be addressed by its fully qualified name.
        {
          type: TypeModel.EnumType,
          name: "MY.org.Enum",
          mappedName: "MyEnum",
        },
        {
          type: TypeModel.ComplexType,
          name: "MY.org.Complex",
          mappedName: "MyComplex",
        },
        {
          type: TypeModel.EntityType,
          name: "MY.org.Child",
          mappedName: "MyChild",
        },
        {
          type: TypeModel.Any,
          name: "NS1.Entity",
          mappedName: "MyEntity",
        },
        {
          type: TypeModel.OperationType,
          name: "NS*2.BoundFunc",
          mappedName: "BoundFunc_v2",
        },
        {
          type: TypeModel.Any,
          name: "NS3.BoundFunc",
          mappedName: "BoundFunc_v3",
        },
        // ...
      ],
    },
    renamingByRegExp: {
      // ....
      byTypeAndName: [
        // renaming "MY.org.xyz" to "My_xyz"
        {
          type: TypeModel.Any,
          name: /MY\.org\.(.*)/,
          mappedName: `My_$1}`,
        },
        // renaming with regexp: "NS1.xyz" || "NS*2.xyz" || ... => "xyz_NS1" ||  "xyz_NS2" || ...
        {
          type: TypeModel.Any,
          name: /NS(\*)?(.)\.(.+)/,
          mappedName: "$3_NS$2",
        },
      ],
    },
  },
}
```

See the [hand made examples](https://github.com/odata2ts/odata2ts/tree/main/examples/hand-made) package for more details and examples, of course.

**Comment by texttechne** [comment]
Hi @hakimio,

all issues you've raised should be addressed now with release `0.33.0` of `@odata2ts/odata2ts`:

* namespaces are now fully supported as explained in the last comment
  * solves the error "maximum call stack..."
  * avoids name clashes
* by default the auto-detected service name is now ensured to be JS compatible
  * solves the error regarding invalid class name `webapi.ModelsService` => `WebapiModelsService`
  * you could have and probably want to use the option `serviceName` to name your service yourself
* >One more minor issue: the generator says `Emitting 3 TS files` even when it emits only one (`mode: Modes.models`).
  *  fixed this to report the correct amount of files
  * added the file names

Please test yourself and close this issue if it works for you with the newest version.

**Comment by hakimio** [comment]
Thank you. I'll test it out sometime this week and let you know if everything's working well.

**Comment by hakimio** [comment]
@texttechne the issues described in the bug report seem to be fixed.
Just found a minor issue with filter builder: it doesn't seem to be possible to create a filter like `MyEntity/any()` since `any()` filter in `odata2ts` requires filter function.
Anyway, I can create a new bug report for that.
