### ISSUE TITLE
Handling Large APIs

### ISSUE THREAD

**Issue by texttechne** [odata2ts/odata2ts#251]
Some APIs, especially from the Microsoft universe, tend to be quite large (up to 16mb). In these scenarios the generation fails at some point with `RangeError: Maximum call stack size exceeded`. While we know this error mainly from faulty recursive implementations, it is to be taken literally here: It's just too much stuff.

### Related Issues and Persons
* #246
  * this edmx file is "only" 250KB large
  * generation with `js_dts` fails with said error
  * generation with `ts` succeeds, but compiling the generated stuff will fail with said error
* #244 
  *  generation in `mode=models` takes too long for a 16mb file
  * @d9k solved this by filtering the XML beforehand => only certain EntityTypes are included
* @erik-kers brings up another issue but is ultimately confronted with the same problem
  * EDMX = 16MB
  * it's the full Microsoft Dynamics 365 API 

### For Comparison
* EDMX of Trippin service: 9KB
* Generated Q-Objects: 10KB
* Generated models: 15KB
* Generated Services: 47KB

### Problem
All models, qobjects & services are bundled into their own file. However, this approach has it's limits and I think that those examples are already hitting this limit.

On the other hand: Who wants to generate the complete API or makes use of the full API?
As @d9k already showed: Filtering should be the primary approach here I think.

### Solution Approach 1: Generate Scalable File Structure
At least I want to test if the generation succeeds when files are split up in a scalable way. Each entity would get it's own folder including one file for the models, one file for the q-objects and one file for its services.

### Solution Approach 2: Filtering via Include & Exclude Options
Different scenarios:
* model generation: include & exclude would only target `EntityType`, `ComplexType` and `EnumType`
  * however, there still might exist dependencies between those types 
* full client generation: include & exclude would need to target `EntitySet`, `Singleton`, `FunctionImport` and `ActionImport` elements
  * so here it would be more like specifying the relevant entry points for the API

@erik-kers & @JuncalLP: Would that work for you? I mean filtering the API by using the entry points? Could you extend your examples (both in private repos) to name those entry points which would be relevant for you?

### Open For Suggestions
Any suggestions are welcome...

**Comment by hakimio** [comment]
When splitting into multiple files, might be a good idea to also create separate folders for different namespaces. This way users wouldn't need to deal with duplicates in most cases.
That's how [cds-typer](https://github.com/cap-js/cds-typer) generates it's TS model files.

**Comment by texttechne** [comment]
> When splitting into multiple files, might be a good idea to also create separate folders for different namespaces. This way users wouldn't need to deal with duplicates in most cases.

Yes and no. While this would solve the issue of duplicate names you still get to the very same problem when importing those same named classes:
```
import { MyEntityService } from "ns1/myEntity";
import { MyEntityService } from "ns2/myEntity"; // <-- same problem again
```
This would occur in the generated service classes most likely....

So the best odata2ts could do here, is to rename the import:
```
import { MyEntityService } from "ns1/myEntity";
import { MyEntityService as MyEntityService2 } from "ns2/myEntity"; // <-- same problem again
```
Do you think this improves things?

**Comment by JuncalLP** [comment]
Hi there @texttechne 

Ideal solution IMHO would be Approach 1. Approach 2 would be a nice workaround and a way for the library to offer more flexibility, for sure, but.. where's logic to 'cut off' the EDMX? Maybe not all EntityTypes, but a vast majority are relevant to the project we're migrating. As I understand Approach 2, we'd have to remove what's not used right now, keep adding classes as they are needed... until the point where we hit this problem again.

**Comment by erik-kers** [comment]
@texttechne I will update the repo to include a few different entitysets. 
What I wonder is, wouldn't this approach quickly end up in the same issue again considering the many relationships between the different entity types. 

Take a look at contact for an example:
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/contact?view=dataverse-latest

Say you would specifiy "contact" as an included EntityType and perhaps "contacts" as an included EntitySet. Would odata2ts then have to implicitly include all the related Entities?

**Comment by texttechne** [comment]
@erik-kers & @JuncalLP,
first of all, thanks for the feedback!

Secondly, yes odata2ts would need to find out those dependencies and include them automatically. The idea I was trying to sketch:
* you specify via configuration an entry point (use case: full client) => I need the following entitySets
* odata2ts would then find all related dependencies and starts it generation process

Probably this would end up being an extra program which does this kind of analysis....

While your use case  @JuncalLP  should be comfortably covered by solution approach 1, I see the next problem for these 16MB services. You probably don't want to generate >75MB TS code, right? And even for your 250kb service, do you really need all of those EntityTypes and EntitySets?
* generation will take long, that is if I manage to develop this stream like output behaviour
* I can't imagine a web app to use the full API, so there's simply a lot of dead generated code lying around

So my question really is: Can you imagine to specify those entry points?
I'm thinking ofthese typical `include` and `exclude` configurations... like tsconfig for example...

**Comment by JuncalLP** [comment]
@texttechne if including an entity would make odata2ts navigate relationships and include dependencies the result would be ¿the same? It's the same behavior from [ODataConventionModelBuilder](https://learn.microsoft.com/en-us/odata/webapi/convention-model-builder) that got every EntityType included in the EDMX. So I would have to explicitly exclude stuff. ODataConventionModelBuilder offers a way to do this:
![imagen](https://github.com/odata2ts/odata2ts/assets/92026660/85750fcc-79b4-4820-aea8-da651df2beed)
but I'd like to avoid this approach because, while there are a few EntityTypes that can clearly be excluded, the line on what to exclude soon becomes blurry, and I can't be sure about what will I need in the future, nor about how much I need removed for the service generation to work. Also, the model is still evolving, entities (and entity properties) can be added or removed. So I could have everything working via exclude, find myself having to add a few new EntityTypes + Sets, then it's too much again and service generation wouldn't work again... I just don't see the include/exclude approach for my use case.

**Comment by texttechne** [comment]
@JuncalLP ok, thanks for the background that makes sense!

**Comment by hakimio** [comment]
> Yes and no. While this would solve the issue of duplicate names you still get to the very same problem when importing those same named classes:

For internal use in the generated code you can prefix imported types with a namespace like this:
```ts
import type * as my_ns1 from "./my/ns1";
import type * as my_ns2 from "./my/ns2";

// Then you can use the entities without having to worry about name clashes
export class MyEntitySetService extends EntitySetServiceV4<my_ns1.MyEntity> {}
```

And the users of the generated code should take care of the name clashes in their code themselves. This shouldn't be responsibility of the library.

**Comment by texttechne** [comment]
Hi,

so I've refactored the generator, so that it now also supports an "unbundled mode".
By default, the old bundling logic remains. Use option `bundledFileGeneration: false`  (root config or service level config) to get more than 3 files 😄 

A lot of bugfixes went into the refactoring as the MS Dynamics API makes use of any edge case I haven't thought of so far. The unbundled mode actually helped to discover those issues...

On the downside: OData allows for bidirectional relations, which leads to circular dependencies. Bundling everything in one file mitigates the problem of circular dependencies. So there's the open question from my side, if such circular dependencies work with your bundlers. I still have to try this with Vite...

However, the unbundled mode doesn't solve the underlying issue with "Maximum Call Stack exceeded". The generation actually works fine when emitting TS, but as soon as this get's typechecked (`tsc`), the error occurs. The same happens when generating `js_dts` or `js` files, only in one go. So in these cases the generation fails directly with this error.

It seems that the types are too complex. [Related issue](https://github.com/microsoft/TypeScript/issues/33460). I cannot find a bug in the code. Experiments with generating less to overcome the error have shown that it's more or less random what to leave out: As soon as the complexity is reduced it might work. Well, it leads me to the conclusion that the typing is just too complex... of course, I might be wrong here...

My next solution approach: Generate an API model for the services. I suspect that TS has problems to use the generated services as types without already fully checking the service...

**Comment by hakimio** [comment]
@texttechne maybe you can put `// @ts-nocheck` in the generated files to avoid `tsc` error?

**Comment by RicardoMoraisPOR** [comment]
@texttechne i would like to thank you for the work done for this update, i'm working on a odata v4 and before the update, the generation itself would take up to 5 minutes and the emitted ts files would have over *290k* lines.

This is no longer an issue after the update, since it doesn't bundle every WebApi class into a single file.

But i would like to mention that the file Qxxx is still being generated and it's empty since the files are not bundled anymore

![image](https://github.com/odata2ts/odata2ts/assets/28900635/b498ee4c-c503-463f-a1ee-6c5d567be6a2)

is this by design?

**Comment by texttechne** [comment]
Hi @RicardoMoraisPOR,
these files would still be needed for unbound operations:
* the parameter model would go into the model file
* the QFunction or QAction would go into the q file
However, if your OData service doesn't feature unbound actions / functions then the files shouldn't be created, of course. Will take a look, but you can also create an issue for that.

I have a couple of questions in return 😄:
* is the generation process now faster for you? Less than the mentioned 5 min?
* do you have any circular dependencies? (madge is a cool tool to find that out)
* and in connection with circular deps: does your bundling still work with the unbundled file generation? Have you tried that?

**Comment by RicardoMoraisPOR** [comment]
- From 5:47 (maximum time) to 14 seconds (maximum time), absurd times for such large xml.
![image](https://github.com/odata2ts/odata2ts/assets/28900635/9f4111e5-3e10-4db2-b2dc-29dbadaead0b)

- When bundled, I indeed had circular dependencies (at least TypeScript was warnings me about it), but now I don't have any (tested with Madge).

Also, some TypeScript errors have disappeared. Initially, I thought I was excluding them in the tsconfig since they are excluded in the eslintrc, but that's not the case. I restarted the TypeScript server repeatedly and not a single TypeScript error appeared."

i haven't tried the service enough to tell you if there's something wrong with it, but in the first 2 days of trying, i have no complains

**Comment by texttechne** [comment]
@RicardoMoraisPOR Thank you so much for the feedback & the stats! Great news!

**Comment by texttechne** [comment]
Hi @RicardoMoraisPOR,
the mentioned extraneous file generation (main model & q-objects files) should be fixed with release `0.34.0` of `@odata2ts/odata2ts`.

**Comment by RicardoMoraisPOR** [comment]
Hello again, i have some updates to give:

I do have **circular dependencies** on my project, despite Madge first test didnt detect anything, `✔ No circular dependency found!`

i have been refreshing the types quite often, and in one of those times, `typescript.tsserver.experimental.enableProjectDiagnostics` option from vscode detected alot of errors in the odata related files. but it went away, that flashing of error made me do a type checking.

I ran `tsc --noEmit --watch --traceResolution -p tsconfig.json` to see if i could find the errors, and it found alot of them.
I guess tsserver probably got overloaded from the enableProjectDiagnostics and just broke 🤷.
 
some were just rules i dont particulary enforce in my project, so i went to see if madge picked some circular deps cause in the error flash i saw one of them.

`madge --circular --extensions ts ./odata`

returned 3108 circular dependencies. i ran a tsc build just to see if it compiles and i got this error https://github.com/odata2ts/odata2ts/issues/243

Any ideas on how to get over this? and i'm sorry for the wrong inputs i gave, the project is still in the early days and it's hard to test it against something

**Comment by texttechne** [comment]
The `max call stack size exceeded` error won't occur now anymore.
Most larger APIs work now. See #246. @RicardoMoraisPOR, please give it a try. 

By the way, the unbundled mode is faster, but both modes work with metadata files up to 1MB. The bundled mode prevents cyclic dependencies, hence it's the default. But for me it's still the question if cyclic dependencies are an issue for the bundlers out there or not...

@erik-kers I don't know if you're still interested in getting the dynamics service to work with odata2ts. If so, you still need a bit patience as I finally need to eliminate some more bugs. But now that the error won't occur I'm finally able to find those bugs and work on them. 

Last but not least I will then add `@ts-nocheck` by default to all generated artefacts. I intend to use `debug: true` to switch that off, so that it's also possible to type check the generated code.

**Comment by RicardoMoraisPOR** [comment]
@texttechne
before the update:
![image](https://github.com/odata2ts/odata2ts/assets/28900635/2b0c743c-be20-4303-933d-3fc2ab2b9d0e)

updated the following packages:
```
"@odata2ts/odata-service": "0.19.0",
"@odata2ts/odata2ts": "0.35.0",
```

after the update: 
![image](https://github.com/odata2ts/odata2ts/assets/28900635/1889ad65-f7b2-4dd7-9b0f-18efaf10c7be)

Once again, thank you for such quick responses

**Comment by erik-kers** [comment]
@texttechne I've been following this issue patiently, and I'm still totally interested to make it work!
I'm very impressed with the effort you have put into this issue (and others). Thans again.

**Comment by texttechne** [comment]
Last change: the generated models won't get prefixed by `// @ts-nocheck`.

Otherwise everything is released with:
* [@odata2ts/odata2ts@0.36.0](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata2ts%400.36.0)

**Comment by erik-kers** [comment]
@texttechne Sorry about the late reply.

I have tested it now. On  `"@odata2ts/odata2ts": "0.37.0",` I get (perhaps unrelated?)
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'rimraf' imported from C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\@odata2ts\odata2ts\lib\cli\serviceGenerationRun.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:951:9)
    at moduleResolve (node:internal/modules/esm/resolve:1000:20)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

On vesrion 0.36.3 I get this error
```
Starting generation process. Service name "dynamics"
Found metadata file at:  ./$metadata.xml
Reading metadata from file: ./$metadata.xml
Prepared to emit JS & DTS files.
Error while running the program NotImplementedError: Unexpected! Inserting syntax kind of InterfaceDeclaration, but ExpressionStatement was inserted.
    at getRangeWithoutCommentsFromArray (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:917:23)
    at insertIntoBracesOrSourceFileWithGetChildren (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:2523:12)
    at SourceFile._insertChildren (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11489:20)
    at SourceFile.insertInterfaces (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11301:25)
    at SourceFile.addInterfaces (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11295:25)
    at SourceFile.addInterface (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11292:25)
    at ModelGenerator.generateModel (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\@odata2ts\odata2ts\lib\generator\ModelGenerator.js:97:24)
    at C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\@odata2ts\odata2ts\lib\generator\ModelGenerator.js:54:18
    at Array.map (<anonymous>)
    at ModelGenerator.generateEntityTypeModels (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\@odata2ts\odata2ts\lib\generator\ModelGenerator.js:47:48)
    ```

**Comment by hakimio** [comment]
It seems `rimraf` is [used in the library](https://github.com/odata2ts/odata2ts/blob/520f6fee95b7c5616ce163dd11851b5de15a8d04/packages/odata2ts/src/cli/serviceGenerationRun.ts#L3) but not included in the dependencies.
Does the latest version work for you if you manually install `rimraf`?

**Comment by erik-kers** [comment]
@hakimio Thanks, I've installed rimraf and that solved the first problem. But it now looks like i recieve the same error as on v 0.36.*.

Should I try some other configuration?

Currently setting no options
```
import { ConfigFileOptions } from "@odata2ts/odata2ts";

const config: ConfigFileOptions = {
  services: {
    dynamics: {
      serviceName: "dynamics",
      source: "./$metadata.xml",
      output: "generated/dynamics",
    },
  },
};

export default config;

```
**The error:**
```
Loaded config file:  odata2ts.config.ts
---------------------------
Starting generation process. Service name "dynamics"
Found metadata file at:  ./$metadata.xml
Reading metadata from file: ./$metadata.xml
Error while running the program NotImplementedError: Unexpected! Inserting syntax kind of InterfaceDeclaration, but ExpressionStatement was inserted.
    at getRangeWithoutCommentsFromArray (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:917:23)
    at insertIntoBracesOrSourceFileWithGetChildren (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:2523:12)
    at SourceFile._insertChildren (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11489:20)
    at SourceFile.insertInterfaces (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11301:25)
    at SourceFile.addInterfaces (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11295:25)
    at SourceFile.addInterface (C:\Users\erik.kers\repositories\Privat\dynamics-metadata\node_modules\ts-morph\dist\ts-morph.js:11292:25)
    at ModelGenerator.generateModel (file:///C:/Users/erik.kers/repositories/Privat/dynamics-metadata/node_modules/@odata2ts/odata2ts/lib/generator/ModelGenerator.js:93:24)
    at file:///C:/Users/erik.kers/repositories/Privat/dynamics-metadata/node_modules/@odata2ts/odata2ts/lib/generator/ModelGenerator.js:50:18
    at Array.map (<anonymous>)
    at ModelGenerator.generateEntityTypeModels (file:///C:/Users/erik.kers/repositories/Privat/dynamics-metadata/node_modules/@odata2ts/odata2ts/lib/generator/ModelGenerator.js:43:48)
```

**Comment by hakimio** [comment]
You can try different emit modes to see if it helps:
```ts
import {ConfigFileOptions, EmitModes, Modes} from '@odata2ts/odata2ts';

const config: ConfigFileOptions = {
    mode: Modes.service,
    skipEditableModels: true,
    skipIdModels: true,
    skipOperations: true,
    skipComments: true,
    emitMode: EmitModes.ts,
    services: {
        dynamics: {
            serviceName: "dynamics",
            source: "$metadata.xml",
            output: "generated/dynamics",
        },
    },
};

export default config;
```

**Comment by texttechne** [comment]
Hi @erik-kers,

sorry, f*cked up the dependencies, obviously. Thanks @hakimio for the pointer there. I will fix this in the evening.

The most important settings in your case are
*  `bundledFileGeneration: false`
* `emitMode: EmitModes.js_dts` => as you don't want to compile that within your project

But I will need to take a look again. Looks like an odata2ts bug for now... So, to go the extra mile, I'll update your example repo until it works...

**Comment by KODIKAS-NL** [comment]
> You can try different emit modes to see if it helps:
> 
> ```ts
> import {ConfigFileOptions, EmitModes, Modes} from '@odata2ts/odata2ts';
> 
> const config: ConfigFileOptions = {
>     mode: Modes.service,
>     skipEditableModels: true,
>     skipIdModels: true,
>     skipOperations: true,
>     skipComments: true,
>     emitMode: EmitModes.ts,
>     services: {
>         dynamics: {
>             serviceName: "dynamics",
>             source: "$metadata.xml",
>             output: "generated/dynamics",
>         },
>     },
> };
> 
> export default config;
> ```

I'm getting the exact same error as @erik-kers when generating types for microsoft dynamics.
Tried all the different emit modes, always the same error:

> Error while running the program NotImplementedError: Unexpected! Inserting syntax kind of InterfaceDeclaration, but ExpressionStatement was inserted.

**Comment by KODIKAS-NL** [comment]
> Cheers @KODIKAS-NL, then it's definitely a odata2ts bug. Will take a look.
> 
> However, can one of you please create a new issue for this along this line: "Support MS Dynamics API".

Here you go: https://github.com/odata2ts/odata2ts/issues/310

Thanks!
