### ISSUE TITLE
Support for odata `any()` fluent filter with empty filter body

### ISSUE THREAD

**Issue by hakimio** [odata2ts/odata2ts#252]
Right now odata2ts filter builder supports expressions like `~/Movies/?$filter=any(Actors,any(it/Tags, it eq 'Favorite'))` but does not support a valid filter like the following: `~/Movies/?$filter=Tags/any()` where `any()` filter body is empty.

**Comment by texttechne** [comment]
With release `@odata2ts/odata-query-objects@0.20.1` there's now support for empty lambda operators.
So these usages are valid now:
```ts
qPerson.trips.any().toString() === "Trips/any()"
qPerson.trips.any(() => {})).toString  === "Trips/any()"
```
The same goes for `all`, of course. 

See [tests](https://github.com/odata2ts/odata2ts/commit/6ce3742f8a8c1f07d23ef2f56745e31654c9a6d9)

**Comment by hakimio** [comment]
Seems to work well. Thank you 🙂
