### ISSUE TITLE
Error when sending payloads with OData type annotation

### ISSUE THREAD

**Issue by oartyshko** [odata2ts/odata2ts#257]
While trying to call a method of `odata2ts` generated service with `@odata.type` annotation inside a POST payload to create an Entity that contains a complex type, I encountered the following error: 
```
app-error-handler.ts:35 Error: Property [@odata.type] not found (in strict mode)! Known user model props: 
    at QueryObject.js:100:27
    at Array.reduce (<anonymous>)
    at QueryObject.js:87:42
    at Array.map (<anonymous>)
    at Configuration.convertToOData (QueryObject.js:86:31)
    ...
```

The error occurred here:
https://github.com/odata2ts/odata2ts/blob/main/packages/odata-query-objects/src/QueryObject.ts#L158

Here is an example of POST payload for a complex type entity: https://www.odata.org/getting-started/basic-tutorial/#modifyData.

It seems that the library is not recognizing the `@odata.type` annotation.

**Comment by texttechne** [comment]
Hi @oartyshko,

the changes:
1. convertTo doesn't throw if it meets unannounced properties (wrong default)
2. Annoations or better to say "control information" are now supported by default for `create`, `patch` and `update`

If you're inclined to check the spec against my understanding (as it is laid out here: #261) you're more than welcome. Open any discussion / issue if you find something.

Released with 
* `@odata2ts/odata2ts` version `0.33.2`
* `@odata2ts/odata-service` version `0.18.0` 

If the release fixes your issue, then please close the ticket.

**Comment by oartyshko** [comment]
Hi @texttechne!

Thanks a lot for this improvement! 👍  I've just tested it ✅  It works perfectly!
