### ISSUE TITLE
[Bug Report] Nested any/all

### ISSUE THREAD

**Issue by JuncalLP** [odata2ts/odata2ts#265]
odata2ts version: 0.31.1     
API: Microsoft.AspNetCore.OData 8.2.4

Triying to do a query with nested any/all using query builder gives server response

"The range variable 'a' has already been declared."

since every any/all uses the same placeholder 'a'

**Comment by texttechne** [comment]
Hi @JuncalLP,

using custom prefixes is actually supported: It's the second parameter of the `any` or `all` function.
From the tests:
```ts
  test("any with prefix", () => {
    const result = createToTest()
      .any((qTest) => qTest.id.gt(18), "testing")
      .toString();
    expect(result).toBe("test/any(testing:testing/id gt 18)");
  });
```

Added a todo for the documentation.

I close this issue assuming that this solves your problem.
