### ISSUE TITLE
Support AbortSignal in options for FetchClient

### ISSUE THREAD

**Issue by brandonryan** [odata2ts/odata2ts#276]
add `signal?: AbortSignal` to `FetchRequestConfig` to allow clients to cancel requests.

Right now in my react application, when a filter changes, but a request is in flight, I have no way to cancel the old request. Adding this feature would solve that problem.

**Comment by texttechne** [comment]
Hi @brandonryan,
nice point, `signal` will be added to: https://github.com/odata2ts/http-client/blob/main/packages/fetch/src/FetchRequestConfig.ts#L9

Actually, it's "only" the typing of the fetch request options that is over-restrictive. So you can pass any valid [fetch request config}(https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options) including the `signal` property. Just `@ts-ignore` it for now as workaround.

**Comment by texttechne** [comment]
Solved with release `@odata2ts/http-client-fetch@0.8.0`.

Please test and close this issue if successful.

**Comment by brandonryan** [comment]
Oops, missed this. Yes it is fixed. thank you!
