### ISSUE TITLE
Adding the type modifier for type only imports

### ISSUE THREAD

**Issue by TimRensen** [odata2ts/odata2ts#279]
### Discussed in https://github.com/odata2ts/odata2ts/discussions/277

When enabling the option `verbatimModuleSyntax` in the tsconfig `compilerOptions` the following error is displayed while building a project with a type-checker.
It would make sense to add the `type` modifier for type-only imports in the generated files.

`error TS1484: '...' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.`

This problem is also highlighted in the generated QObjects and Services:
![image](https://github.com/odata2ts/odata2ts/assets/37070855/a4051bf5-0c14-4378-b06c-23d978083240)
![image](https://github.com/odata2ts/odata2ts/assets/37070855/c7d7ad5b-852d-423f-bdb9-8664b6691b34)

**Comment by texttechne** [comment]
Hi @TimRensen and @brease-colin,

this issue should be resolved with:
* [@odata2ts/odata2ts@0.36.1](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata2ts%400.36.1)
* main implementation in `0.36.0`

Please close the issue if you can confirm that this is working in your project.

**Comment by texttechne** [comment]
Tested it myself against a suitable project. Required a fix.

Released with:
* [@odata2ts/odata2ts@0.36.2](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata2ts%400.36.2)
