### ISSUE TITLE
ODataDomainEntitiesService.ts: getDefaultHeaders error (Expected 2-3 arguments, but got 4)

### ISSUE THREAD

**Issue by brease-colin** [odata2ts/odata2ts#280]
I am using @odata2ts/odata2ts v0.35.0 and @odata2ts/converter-common 0.2.0. I'm using it to generate TS files of a .Net Core OData v4 web service. The following is my config:

```
services: {
        v1: {
            sourceUrl: 'http://[url]/v1',
            source: '$metadata',
            output: 'src/odata/v1',
            refreshFile: true,
            emitMode: EmitModes.ts,
            allowRenaming: true,
            v4BigNumberAsString: true,
        }
    },
    converters: [
        {
            module: "@odata2ts/converter-common",
            use: ["dateTimeOffsetToDateConverter", "simpleDurationConverter"],
        },
    ],
```

I'm running into the following error in the generated ODataDomainEntitiesService.ts file:
```
error TS2554: Expected 2-3 arguments, but got 4.

return client.post(url, {}, requestConfig, getDefaultHeaders());
```
(getDefaultHeaders probably needs to be combined with requestConfig into a single object value?)

**Comment by texttechne** [comment]
Hi @brease-colin,
this sounds like the version of the http client you have chosen (e.g. `@odata2ts/http-client-fetch`) is out of date. Please update it and try again.

Otherwise I would need a minimal example in form of the metadata file.

**Comment by brease-colin** [comment]
To be honest, I did not install any odata2ts http client previously. I hadn't actually executed any requests yet, was just checking how the output would be. :) I have now installed the latest version of that library, but to no avail though. Do I also have to configure it somewhere for the generated code to know which one to use?

Maybe, like my other issue, it's another case of skipping all type checking for this generated code? Because the actual http client that'll be used will probably work well.

Either way, don't know if it'll help, but the type of the client that it's trying to access is:

```
const client: in out ClientType extends ODataHttpClient<any>
```

A 'go to definition' leads me to
```
node_modules\@odata2ts\http-client-api\lib\ODataHttpClient.d.ts
```

And the get function for example looks like this:

```
get<ResponseModel>(url: string, requestConfig?: RequestConfig): ODataResponse<ResponseModel>;
```

**Comment by nile4000** [comment]
works for me when i use emitMode: EmitModes.dts, but same error for EmitModes.ts

**Comment by texttechne** [comment]
Should be due to an outdated dependency of `@odata2ts/odata-query-objects`.

Fixed in:
* [@odata2ts/odata-query-objects@0.22.0](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-query-objects%400.22.0)

Imported by:
* [@odata2ts/odata-service@0.19.1](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-service%400.19.1)
* [@odata2ts/odata2ts@0.36.0](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata2ts%400.36.0)
