### ISSUE TITLE
Use parameter alias for complex function parameters

### ISSUE THREAD

**Issue by aschmidt93** [odata2ts/odata2ts#285]
Hi there,

given an (unbound) function with a complex/structured parameter type, e.g.

```cds

function someFunction(id: String, params : Params) returns String;

type Params {
  foo: String;
  bar : String;
}

```

the URL generated by odata2ts uses inline parameter syntax

```
GET /someFunction(id='123',params%3D%7B%22foo%22%3A%22asd%22%2C%22bar%3A%22fgh%22%7D)
```

However, some OData implementations require that complex parameters are passed as parameter aliases instead, e.g. CAP. See also https://community.sap.com/t5/sap-business-technology-platform-discussions/cap-crash-on-complex-function-parameter/m-p/13725659.

Thus, the request should be
```
GET /someFunction(id='123',params=@params)?@params={"foo":"asd","bar:"fgh"}
```

**Comment by texttechne** [comment]
Hi @aschmidt93,
according to [the spec](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ParameterAliases) this behaviour would be optional:

> Parameter aliases can be used in place of literal values in entity keys, function parameters, or within a $compute, $filter or $orderby expression.

And I actually hoped I would never need to implement this... duh... 

So this extra requirement boils down to function parameters, I guess. Do you know any place where you would need to use parameter aliases for entity keys, filter queries, $compute or $orderby? As these are never complex attributes it shouldn't be necessary, but maybe you can think of any other use case...

**Comment by aschmidt93** [comment]
Hi @texttechne,

I agree that it should be optional and I pointed it out to the CAP developers. However, currently this is required in CAP :(

> Do you know any place where you would need to use parameter aliases for entity keys, filter queries, $compute or $orderby?

Fortunately, I don't know of any other place.

**Comment by aschmidt93** [comment]
Apparently, it isn't optional after all, see https://community.sap.com/t5/sap-business-technology-platform-discussions/cap-crash-on-complex-function-parameter/m-p/13730516/highlight/true#M2007

**Comment by texttechne** [comment]
Thanks for keeping me updated. 
Ok, the relevant spec is the one about [URL conventions](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_ComplexandCollectionLiterals) then:

> Complex literals and collection literals in URLs are represented as JSON objects and arrays according to the arrayOrObject rule in [[OData-ABNF]](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#ABNF). Such literals MUST NOT appear in the path portion of the URL but can be passed to bound [functions](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingFunctions) and function imports in path segments by using [parameter aliases](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_ParameterAliases).

Damn, I suck at finding the right spec then... But, at least, this highlights that it's all about function parameters and not entity keys, filters or the like.

**Comment by texttechne** [comment]
Great, looks quite alright. Just some minor improvements from my side.
If fixed, I try to release this tonight.

**Comment by aschmidt93** [comment]
I assume I missed something as you reopened the issue?

**Comment by texttechne** [comment]
Nope, just missed to make my comments.

Released with: [@odata2ts/odata-query-objects@0.23.0](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-query-objects%400.23.0)

@aschmidt93 please test and close this issue if it works.

**Comment by aschmidt93** [comment]
I've prepared another PR with a fix that was required for URI encoded values.

**Comment by texttechne** [comment]
Released with:
* [@odata2ts/odata-query-objects@0.23.1](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-query-objects%400.23.1)
* imported by [@odata2ts/odata-service@0.19.3](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-service%400.19.3)

**Comment by texttechne** [comment]
Hi @aschmidt93,
can you verify that it works now? Can we close this issue?

**Comment by aschmidt93** [comment]
Ofc, works :)
