### ISSUE TITLE
[Feature Request] http-client-fetch: return responseData as part of error if !response.ok

### ISSUE THREAD

**Issue by ralfnl** [odata2ts/odata2ts#299]
Hi,

We are integrating with SAP using your `@odata2ts/http-client-fetch` package. Everything works well, but SAP only provides very minimal and static error message if there is a validation error.  The actual error is returned in the response body.

Currently, `fetchResponse.json()` is performed within the `http-client-fetch` package, making it impossible to retrieve the body for further use. The JSON body is awaited and read; but -in SAP case- only the general message is added to the error.

Request:
It would be helpful to return the `responseData` value as part of the response object in the `FetchClientError`.

![image](https://github.com/user-attachments/assets/f74d56f0-d268-4ea4-b35e-a7ea348b022b)
Above implementation is maybe a bit rough. But provided us the additional insight we needed.

**Comment by texttechne** [comment]
Hi @ralfnl,

I understand that you only get a quite generic error message from the payload. So you're telling me that:
* you get proper JSON as response data
* somewhere in this response data is a more fine-grained validation message to be found

If I've got that correct, then you would be fine with defining your own `ErrorMessageRetriever`. Each HTTPClient allows to set this via `setErrorMessageRetriever(getErrorMsg: ErrorMessageRetriever)`, which is not documented 😅. But as can be seen from your screenshot: This method defines the error message that is passed into the `FetchClientError`.

But in any case, can you please show me this kind of response structure, you're talking about?

**Comment by ralfnl** [comment]
Hi @texttechne,

Thank you for your swift response. I had a try on the 'hidden feature' and indeed it provides me with the original body. I think that could partly help us out to at least show 'better' error messages. Being able to access the entire response JSON as context on the error would be even greater. We would like to log that for easier debugging.

Cramming the entire response body into the string message would leave a bit of a hackey result. 🙃

As requested the SAP response. Both in SAP and Dutch, so hold tight 😁

```json
{
    "error": {
        "code": "ZPS/031",
        "message": "Er zijn validatiefouten opgetreden",
        "@SAP__common.ExceptionCategory": "Provider_Application_Error",
        "details": [
            {
                "code": "ZPS/044",
                "message": "Geen standaardproject gedefinieerd voor vestiging XXX, projectprofiel XXX",
                "@SAP__common.Severity": "error",
                "@SAP__common.numericSeverity": 4
            }
        ],
        "innererror": {
            "ErrorDetails": {
                "@SAP__common.Application": {
                    "ComponentId": "XXX",
                    "ServiceRepository": "XXX",
                    "ServiceId": "XXX",
                    "ServiceVersion": "0001"
                },
                "@SAP__common.TransactionId": "XXX",
                "@SAP__common.Timestamp": "XXX",
                "@SAP__common.ErrorResolution": {
                    "Analysis": "XXX",
                    "Note": "XXX"
                }
            }
        }
    }
}
```

**Comment by texttechne** [comment]
Hi @ralfnl,

thanks for the example.

Here you go:
* [Pull Request](https://github.com/odata2ts/http-client/pull/22)
* So you get the parsed JSON as `responseData` from the `FetchClientError`
* Of course, if `fetch` or the conversion to JSON failed the field is `undefined`

Released with `@odata2ts/http-client-fetch@0.8.0`

**Comment by texttechne** [comment]
Please test and close the issue if successful.

**Comment by ralfnl** [comment]
Thank you @texttechne ! This works like a charm. Thank you for your swift response.
