### ISSUE TITLE
OData V2 generate wrong Set Path with parameters

### ISSUE THREAD

**Issue by p-mathias** [odata2ts/odata2ts#309]
Got here an sapui5 app with abap 7.50 backend,
which i try to convert to vuejs.

And we found a mismatch of data service from sapui5 vs odata2ts:
sapui5 :
http://[localhost:5173/ZAAG_PA_OP_SRV/ZAAG_PA_OP_C_DEP_VH(p_role='HRWP_FK',p_keyDate=datetime'2024-08-28T01:01:01')/Set?sap-client=200](http://localhost:5173/ZAAG_PA_OP_SRV/ZAAG_PA_OP_C_DEP_VH(p_role='HRWP_FK',p_keyDate=datetime'2024-08-28T01:01:01')/Set?sap-client=200)

odata2ts (use the normal interface)
```js
const oDataService = ref(
  new ZaagPaOpSrvService(httpClient, odata2tsConfig.services.ZAAG_PA_OP.sourceUrl, true)
)

export async function getDepDataOCall() {
  return await oDataService.value
    .zaagPaOpCDepVh({ pRole: 'HRWP_FK', pKeyDate: '2024-08-28T01:01:01' })
    .query()
}
```
produce: http://[localhost:5173/ZAAG_PA_OP_SRV/ZAAG_PA_OP_C_DEP_VH(p_role='HRWP_FK',p_keyDate=datetime'2024-08-28T01:01:01')?sap-client=200](http://localhost:5173/ZAAG_PA_OP_SRV/ZAAG_PA_OP_C_DEP_VH(p_role='HRWP_FK',p_keyDate=datetime'2024-08-28T01:01:01')?sap-client=200)

(notice the missing Set)

odata2ts (use the set interface)
```js
const oDataService = ref(
  new ZaagPaOpSrvService(httpClient, odata2tsConfig.services.ZAAG_PA_OP.sourceUrl, true)
)

export async function getDepDataOCall() {
  return await oDataService.value
    .zaagPaOpCDepVhSet({ pRole: 'HRWP_FK', pKeyDate: '2024-08-28T01:01:01' })
    .query()
}
```

produce: http://localhost:5173/ZAAG_PA_OP_SRV/ZAAG_PA_OP_C_DEP_VHSet(p_role='HRWP_FK',p_keyDate=datetime'2024-08-28T01%3A01%3A01')?sap-client=200

Notice that the "Set" is before "(" and not after ")"

Also in der Set interface he complain about missing departmentid, when you look at the sapui5 version didn't used it:
![image](https://github.com/user-attachments/assets/842ca806-b2b9-480f-9537-3bc50d4d9d35)
in the non Set Interface the parameter is not asked/required.

Config:
```js
import { type ConfigFileOptions, EmitModes, Modes } from '@odata2ts/odata2ts'

const config: ConfigFileOptions = {
  mode: Modes.all,
  allowRenaming: true,
  emitMode: EmitModes.ts,
  services: {
    ZAAG_PA_OP: {
      sourceUrl: 'http://localhost:5173/ZAAG_PA_OP_SRV',
      source: 'resource/ZAAG_PA_OP_C_POSITION_metadata.xml',
      output: 'src/res/ZAAG_PA_OP'
    }
  }
}

export default config
```

**Comment by texttechne** [comment]
Hi @p-mathias,

please provide the EDMX for this scenario.

To get something like this (
`http://localhost:5173/ZAAG_PA_OP_SRV/ZAAG_PA_OP_C_DEP_VH(p_role='HRWP_FK',p_keyDate=datetime'2024-08-28T01:01:01')/Set`)
you would rather call the service like this:
```
 await oDataService.value.zaagPaOpCDepVh({ pRole: 'HRWP_FK', pKeyDate: '2024-08-28T01:01:01' }).set().query()
```
So you're are getting an `EntityService` for the entity `ZAAG_PA_OP_C_DEP_VH` and navigate to the `NavigationProperty` called `Set`. There you would execute the query.

Then again, maybe SAP does something weired here. However, I cannot judge this without a look at the EDMX.

**Comment by p-mathias** [comment]
Hi @texttechne ,

dunno if i can share this file,
but by calling set() the odata query works fine,
so it was a mistake from my side, sry
