### ISSUE TITLE
Add QFilterExpression-like functionality for expand

### ISSUE THREAD

**Issue by brease-colin** [odata2ts/odata2ts#321]
As discussed [here](https://github.com/odata2ts/odata2ts/discussions/320), there's a workaround to add custom filter expressions to a query and it can be used in a hacky way to also add a custom expand, but it would be nice if there were a QExpandExpression or something to make that easier.

**Comment by texttechne** [comment]
#329 solves the original problem.

I'm closing this as I don't see any further use case right now.
