### ISSUE TITLE
Generate flat or statement instead of nesting when filtering with in operator

### ISSUE THREAD

**Issue by aabdellah** [odata2ts/odata2ts#337]
Currently when using the in operator in OData v1 like this example:

`.filter(qContract.contractDetailId.in(...contractLineIds))`

the query parameter output is in the nested form like this:

`$filter=(((((((((((((((((((((((ContractId/Id eq '' or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '') or ContractId/Id eq '')`

which causes an error as the recursion limit for or queries is reached when `contractLineIds` is above 11 on MS CRM.

On the other hand, when using the flat or expression, which could be achieved with this custom `QFilterExpression`:

`.filter(
            new QFilterExpression(
              `(${contractLineIds
                .map((id) => `ContractDetailId eq guid'${id}'`)
                .join(" or ")})`
            )
          )`

it works fine without any issues with resulting query parameter output of:

`$filter=(ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '' or ContractDetailId/Id eq '')`

This works successfully and performs the join as required and the server doesn't complain with multiple values of `ContractDetailId`.

Is there any reason why the nested form is generated instead of second one? Is it possible to make it configurable to generate both if the nested form is required?

**Comment by aabdellah** [comment]
Hey @texttechne 

Thanks for your prompt response.

The proposed output for the in statement would work for me. I think it's the same as the `QFilterExpression` I'm using now.

Regarding the outer parentheses, at first our expression didn't have them and it only worked alone and when anding it with other expressions it didn't work as intended. So yes they're important to be added.

**Comment by texttechne** [comment]
Released with 
* [@odata2ts/odata-service@0.22.1](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-service%400.22.1)
* [@odata2ts/odata-query-objects@0.27.0](https://github.com/odata2ts/odata2ts/releases/tag/%40odata2ts%2Fodata-query-objects%400.27.0)

@aabdellah Any verification on your side would be greatly appreciated!
