### ISSUE TITLE
Issue when building with vite

### ISSUE THREAD

**Issue by merlosy** [odata2ts/odata2ts#75]
## Current behavior 

For a vue 3 app **built** with vite, the application fails to start

![image](https://user-images.githubusercontent.com/6629784/203630247-d16f27ab-e603-4c2c-a7a5-5cdf28d9a870.png)

Which brings me to the `QBooleanParam` definition from `@odata2ts/odata-query-objects`

![image](https://user-images.githubusercontent.com/6629784/203634094-f2bf003a-d931-4abb-ae0c-ba1871bc6d2a.png)

However, it works when *serving* the application.

> Disclaimer: This may not be related to this project but instead with `vite` build configuration. But I haven't found a way to make it work for a production build

## Possible area of investigation?

- An issue with how the npm package is built?
- A circular dependency?

**Comment by merlosy** [comment]
Running [madge](https://www.npmjs.com/package/madge) on tag `@odata2ts/odata-query-objects@0.11.1` detects circular dependencies:

![image](https://user-images.githubusercontent.com/6629784/203642888-211111fa-5451-498c-8e2b-d86b073c7999.png)

**Comment by texttechne** [comment]
Hi @merlosy,

I don't know if it solves your problems with vite, but I've removed all circular dependencies. All places were worthwile refactoring.

And thanks for recommending `madge`: nifty little tool. I've integrated it as script into most packages and the CI pipeline will check and fail from now on if any circular deps occur.

**Comment by texttechne** [comment]
@merlosy has been finally released. Would be nice to get feedback here.

**Comment by texttechne** [comment]
Impolitely closed this ticket prematurely.
